import { ASNRecord } from '../types';

export const INITIAL_ASN_DATA: ASNRecord[] = [
  {
    nip: '197508121999031002',
    nama: 'Drs. H. Sa’ban Nuroni, M.A.',
    unitKerja: 'Subbag Tata Usaha',
    jabatan: 'Kepala Kantor',
    kualifikasi: 20, // S2
    kompetensi: 35,
    kinerja: 30, // Sangat Baik
    disiplin: 5,  // Tidak pernah dijatuhi HD
    totalIP: 90,
    status: 'Sudah',
    lastUpdated: '2026-03-15 09:30',
    kualifikasiDetail: 'S2 Magister Agama (20)',
    kompetensiDetail: 'Diklat Kepemimpinan (15), Fungsional (10), Teknis (10)',
    kinerjaDetail: 'Predikat SKP Sangat Baik (30)',
    disiplinDetail: 'Tidak pernah dijatuhi hukuman disiplin (5)',
  },
  {
    nip: '198104192005011003',
    nama: 'Drs. H. Andar Prasetyo, M.A.',
    unitKerja: 'Subbag Tata Usaha',
    jabatan: 'Kasubbag Tata Usaha',
    kualifikasi: 20,
    kompetensi: 38,
    kinerja: 30,
    disiplin: 5,
    totalIP: 93,
    status: 'Sudah',
    lastUpdated: '2026-03-18 11:20',
    kualifikasiDetail: 'S2 Manajemen Pendidikan Islam (20)',
    kompetensiDetail: 'PKA (15), Pelatihan Teknis (13), Workshop (10)',
    kinerjaDetail: 'Predikat SKP Sangat Baik (30)',
    disiplinDetail: 'Tidak pernah dijatuhi hukuman disiplin (5)',
  },
  {
    nip: '198305142009121004',
    nama: 'Supriyanto, S.Ag., M.S.I.',
    unitKerja: 'Seksi Pendidikan Madrasah',
    jabatan: 'Kasi Pendidikan Madrasah',
    kualifikasi: 20,
    kompetensi: 30,
    kinerja: 30,
    disiplin: 5,
    totalIP: 85,
    status: 'Sudah',
    lastUpdated: '2026-03-20 14:15',
    kualifikasiDetail: 'S2 Studi Islam (20)',
    kompetensiDetail: 'Pelatihan Teknis (15), Workshop (15)',
    kinerjaDetail: 'Predikat SKP Sangat Baik (30)',
    disiplinDetail: 'Tidak pernah dijatuhi hukuman disiplin (5)',
  },
  {
    nip: '197906222006041005',
    nama: 'H. Zuhdan Aris, S.Ag., M.A.',
    unitKerja: 'Seksi Bimas Islam',
    jabatan: 'Kasi Bimas Islam',
    kualifikasi: 20,
    kompetensi: 32,
    kinerja: 25,
    disiplin: 5,
    totalIP: 82,
    status: 'Sudah',
    lastUpdated: '2026-03-22 10:45',
    kualifikasiDetail: 'S2 Hukum Islam (20)',
    kompetensiDetail: 'Pelatihan Fungsional (15), Workshop (17)',
    kinerjaDetail: 'Predikat SKP Baik (25)',
    disiplinDetail: 'Tidak pernah dijatuhi hukuman disiplin (5)',
  },
  {
    nip: '198602102011011008',
    nama: 'Taufik Ahmad, S.H.I.',
    unitKerja: 'Seksi Penyelenggaraan Haji dan Umrah',
    jabatan: 'Kasi Penyelenggaraan Haji dan Umrah',
    kualifikasi: 15,
    kompetensi: 25,
    kinerja: 30,
    disiplin: 5,
    totalIP: 75,
    status: 'Sudah',
    lastUpdated: '2026-03-25 08:30',
    kualifikasiDetail: 'S1 Hukum Islam (15)',
    kompetensiDetail: 'Pelatihan Teknis Haji (15), Workshop (10)',
    kinerjaDetail: 'Predikat SKP Sangat Baik (30)',
    disiplinDetail: 'Tidak pernah dijatuhi hukuman disiplin (5)',
  },
  {
    nip: '198007152008011012',
    nama: 'Drs. H. Masrudin',
    unitKerja: 'Seksi PD Pontren',
    jabatan: 'Kasi Pendidikan Diniyah dan Pontren',
    kualifikasi: 15,
    kompetensi: 30,
    kinerja: 25,
    disiplin: 5,
    totalIP: 75,
    status: 'Sudah',
    lastUpdated: '2026-03-26 13:00',
    kualifikasiDetail: 'S1 Dakwah (15)',
    kompetensiDetail: 'Pelatihan Teknis Pesantren (15), Workshop (15)',
    kinerjaDetail: 'Predikat SKP Baik (25)',
    disiplinDetail: 'Tidak pernah dijatuhi hukuman disiplin (5)',
  },
  {
    nip: '198811202015031002',
    nama: 'Fajar Nugroho, S.Pd.I., M.Pd.',
    unitKerja: 'Seksi PAIS',
    jabatan: 'Kasi Pendidikan Agama Islam',
    kualifikasi: 20,
    kompetensi: 35,
    kinerja: 30,
    disiplin: 5,
    totalIP: 90,
    status: 'Sudah',
    lastUpdated: '2026-03-28 15:40',
    kualifikasiDetail: 'S2 Pendidikan Islam (20)',
    kompetensiDetail: 'Pelatihan Teknis (15), Fungsional (10), Workshop (10)',
    kinerjaDetail: 'Predikat SKP Sangat Baik (30)',
    disiplinDetail: 'Tidak pernah dijatuhi hukuman disiplin (5)',
  },
  {
    nip: '198203112009011009',
    nama: 'Wahyudi, S.E.I., M.E.K.',
    unitKerja: 'Penyelenggara Zakat dan Wakaf',
    jabatan: 'Penyelenggara Zawa',
    kualifikasi: 20,
    kompetensi: 32,
    kinerja: 30,
    disiplin: 5,
    totalIP: 87,
    status: 'Sudah',
    lastUpdated: '2026-03-29 16:10',
    kualifikasiDetail: 'S2 Ekonomi Syariah (20)',
    kompetensiDetail: 'Pelatihan Teknis Nazhir (15), Workshop (17)',
    kinerjaDetail: 'Predikat SKP Sangat Baik (30)',
    disiplinDetail: 'Tidak pernah dijatuhi hukuman disiplin (5)',
  },
  {
    nip: '197601052003121001',
    nama: 'Drs. H. Harun Al Rasyid',
    unitKerja: 'KUA Wonosari',
    jabatan: 'Kepala KUA Wonosari / Penghulu Ahli Madya',
    kualifikasi: 15,
    kompetensi: 35,
    kinerja: 30,
    disiplin: 5,
    totalIP: 85,
    status: 'Sudah',
    lastUpdated: '2026-04-01 10:05',
    kualifikasiDetail: 'S1 Syariah (15)',
    kompetensiDetail: 'Diklat Kepenghuluan (15), Fungsional (10), Workshop (10)',
    kinerjaDetail: 'Predikat SKP Sangat Baik (30)',
    disiplinDetail: 'Tidak pernah dijatuhi hukuman disiplin (5)',
  },
  {
    nip: '198409152011011015',
    nama: 'Muhammad Anas, S.Th.I.',
    unitKerja: 'KUA Wonosari',
    jabatan: 'Penghulu Ahli Muda',
    kualifikasi: 15,
    kompetensi: 28,
    kinerja: 25,
    disiplin: 5,
    totalIP: 73,
    status: 'Sudah',
    lastUpdated: '2026-04-02 09:20',
    kualifikasiDetail: 'S1 Tafsir Hadits (15)',
    kompetensiDetail: 'Pelatihan Teknis (15), Workshop (13)',
    kinerjaDetail: 'Predikat SKP Baik (25)',
    disiplinDetail: 'Tidak pernah dijatuhi hukuman disiplin (5)',
  },
  {
    nip: '199002142019032007',
    nama: 'Nurul Hidayati, S.Sos.',
    unitKerja: 'KUA Wonosari',
    jabatan: 'Penyuluh Agama Islam Ahli Pertama',
    kualifikasi: 15,
    kompetensi: 20,
    kinerja: 25,
    disiplin: 5,
    totalIP: 65,
    status: 'Sudah',
    lastUpdated: '2026-04-02 11:30',
    kualifikasiDetail: 'S1 Komunikasi Penyiaran Islam (15)',
    kompetensiDetail: 'Pelatihan Dasar / Teknis (10), Webinar (10)',
    kinerjaDetail: 'Predikat SKP Baik (25)',
    disiplinDetail: 'Tidak pernah dijatuhi hukuman disiplin (5)',
  },
  {
    nip: '198506182010011014',
    nama: 'Bambang Sudarsono, S.Ag.',
    unitKerja: 'KUA Playen',
    jabatan: 'Kepala KUA Playen',
    kualifikasi: 15,
    kompetensi: 34,
    kinerja: 30,
    disiplin: 5,
    totalIP: 84,
    status: 'Sudah',
    lastUpdated: '2026-04-03 14:00',
    kualifikasiDetail: 'S1 Muamalah (15)',
    kompetensiDetail: 'Pelatihan Fungsional (15), Teknis (10), Workshop (9)',
    kinerjaDetail: 'Predikat SKP Sangat Baik (30)',
    disiplinDetail: 'Tidak pernah dijatuhi hukuman disiplin (5)',
  },
  {
    nip: '197804122005011006',
    nama: 'Drs. H. Sukamto, M.Pd.I.',
    unitKerja: 'MAN 1 Gunungkidul',
    jabatan: 'Kepala Madrasah Aliyah',
    kualifikasi: 20,
    kompetensi: 38,
    kinerja: 30,
    disiplin: 5,
    totalIP: 93,
    status: 'Sudah',
    lastUpdated: '2026-04-04 10:15',
    kualifikasiDetail: 'S2 Pendidikan Agama Islam (20)',
    kompetensiDetail: 'Pelatihan Manajerial Kepala Madrasah (15), Teknis (13), Workshop (10)',
    kinerjaDetail: 'Predikat SKP Sangat Baik (30)',
    disiplinDetail: 'Tidak pernah dijatuhi hukuman disiplin (5)',
  },
  {
    nip: '198705252014032003',
    nama: 'Siti Rohmah, S.Pd., M.Sc.',
    unitKerja: 'MAN 1 Gunungkidul',
    jabatan: 'Guru Ahli Muda (Fisika)',
    kualifikasi: 20,
    kompetensi: 32,
    kinerja: 30,
    disiplin: 5,
    totalIP: 87,
    status: 'Sudah',
    lastUpdated: '2026-04-05 08:45',
    kualifikasiDetail: 'S2 Fisika Sains (20)',
    kompetensiDetail: 'Pelatihan Kurikulum Merdeka (15), Workshop (17)',
    kinerjaDetail: 'Predikat SKP Sangat Baik (30)',
    disiplinDetail: 'Tidak pernah dijatuhi hukuman disiplin (5)',
  },
  {
    nip: '197908202007011019',
    nama: 'H. Supriyadi, S.Ag., M.S.I.',
    unitKerja: 'MTsN 1 Gunungkidul',
    jabatan: 'Kepala MTsN 1 Gunungkidul',
    kualifikasi: 20,
    kompetensi: 36,
    kinerja: 30,
    disiplin: 5,
    totalIP: 91,
    status: 'Sudah',
    lastUpdated: '2026-04-05 13:20',
    kualifikasiDetail: 'S2 Manajemen Pendidikan (20)',
    kompetensiDetail: 'Pelatihan Manajerial (15), Teknis (11), Workshop (10)',
    kinerjaDetail: 'Predikat SKP Sangat Baik (30)',
    disiplinDetail: 'Tidak pernah dijatuhi hukuman disiplin (5)',
  },
  {
    nip: '198302172009012011',
    nama: 'Tri Handayani, S.Pd.I.',
    unitKerja: 'MIN 1 Gunungkidul',
    jabatan: 'Kepala MIN 1 Gunungkidul',
    kualifikasi: 15,
    kompetensi: 30,
    kinerja: 30,
    disiplin: 5,
    totalIP: 80,
    status: 'Sudah',
    lastUpdated: '2026-04-06 15:10',
    kualifikasiDetail: 'S1 PGMI (15)',
    kompetensiDetail: 'Pelatihan Manajerial (15), Workshop (15)',
    kinerjaDetail: 'Predikat SKP Sangat Baik (30)',
    disiplinDetail: 'Tidak pernah dijatuhi hukuman disiplin (5)',
  },

  // PEGAWAI DENGAN STATUS "BELUM" MENGISI (Untuk Menguji Input Form & Menu 4 Rekap Belum)
  {
    nip: '198909122019021004',
    nama: 'Agus Setiawan, S.Kom.',
    unitKerja: 'Subbag Tata Usaha',
    jabatan: 'Pranata Komputer Ahli Pertama',
    kualifikasi: 0,
    kompetensi: 0,
    kinerja: 0,
    disiplin: 0,
    totalIP: 0,
    status: 'Belum',
  },
  {
    nip: '199203152020122008',
    nama: 'Dewi Lestari, S.E.',
    unitKerja: 'Subbag Tata Usaha',
    jabatan: 'Analis Perencanaan Anggaran',
    kualifikasi: 0,
    kompetensi: 0,
    kinerja: 0,
    disiplin: 0,
    totalIP: 0,
    status: 'Belum',
  },
  {
    nip: '199407182022031005',
    nama: 'Rizki Kurniawan, S.Pd.',
    unitKerja: 'Seksi Pendidikan Madrasah',
    jabatan: 'Pengelola Data Kurikulum',
    kualifikasi: 0,
    kompetensi: 0,
    kinerja: 0,
    disiplin: 0,
    totalIP: 0,
    status: 'Belum',
  },
  {
    nip: '199105212019031006',
    nama: 'Imam Syafi’i, S.Sy.',
    unitKerja: 'Seksi Bimas Islam',
    jabatan: 'Penyusun Bahan Urusan Agama',
    kualifikasi: 0,
    kompetensi: 0,
    kinerja: 0,
    disiplin: 0,
    totalIP: 0,
    status: 'Belum',
  },
  {
    nip: '199312042020121007',
    nama: 'Arief Budiman, S.E.',
    unitKerja: 'Seksi Penyelenggaraan Haji dan Umrah',
    jabatan: 'Pengelola Keuangan Siskohat',
    kualifikasi: 0,
    kompetensi: 0,
    kinerja: 0,
    disiplin: 0,
    totalIP: 0,
    status: 'Belum',
  },
  {
    nip: '199508112022032010',
    nama: 'Fatimah Az-Zahra, S.Sos.',
    unitKerja: 'Seksi PD Pontren',
    jabatan: 'Pengadministrasi Pondok Pesantren',
    kualifikasi: 0,
    kompetensi: 0,
    kinerja: 0,
    disiplin: 0,
    totalIP: 0,
    status: 'Belum',
  },
  {
    nip: '198802272015031003',
    nama: 'Ahmad Fauzi, S.H.',
    unitKerja: 'KUA Semanu',
    jabatan: 'Penghulu Pertama',
    kualifikasi: 0,
    kompetensi: 0,
    kinerja: 0,
    disiplin: 0,
    totalIP: 0,
    status: 'Belum',
  },
  {
    nip: '199009182019022009',
    nama: 'Lestari Rahayu, S.Ag.',
    unitKerja: 'KUA Karangmojo',
    jabatan: 'Penyuluh Agama Islam',
    kualifikasi: 0,
    kompetensi: 0,
    kinerja: 0,
    disiplin: 0,
    totalIP: 0,
    status: 'Belum',
  },
  {
    nip: '198711032014031004',
    nama: 'Danang Prasetya, S.Fil.I.',
    unitKerja: 'KUA Ponjong',
    jabatan: 'Penghulu Pertama',
    kualifikasi: 0,
    kompetensi: 0,
    kinerja: 0,
    disiplin: 0,
    totalIP: 0,
    status: 'Belum',
  },
  {
    nip: '199201082020122013',
    nama: 'Siti Maryam, S.Pd.',
    unitKerja: 'MAN 1 Gunungkidul',
    jabatan: 'Guru Ahli Pertama (Bahasa Arab)',
    kualifikasi: 0,
    kompetensi: 0,
    kinerja: 0,
    disiplin: 0,
    totalIP: 0,
    status: 'Belum',
  },
  {
    nip: '199304162022031009',
    nama: 'Hendra Saputra, S.Pd.',
    unitKerja: 'MTsN 1 Gunungkidul',
    jabatan: 'Guru Ahli Pertama (Matematika)',
    kualifikasi: 0,
    kompetensi: 0,
    kinerja: 0,
    disiplin: 0,
    totalIP: 0,
    status: 'Belum',
  },
  {
    nip: '199610222023022012',
    nama: 'Anisa Rahmawati, S.Pd.',
    unitKerja: 'MIN 1 Gunungkidul',
    jabatan: 'Guru Kelas Pertama',
    kualifikasi: 0,
    kompetensi: 0,
    kinerja: 0,
    disiplin: 0,
    totalIP: 0,
    status: 'Belum',
  },
];
